[phases.setup]
pkgs = ["php82", "php82Extensions.bcmath", "php82Extensions.gd", "php82Extensions.mbstring", "php82Extensions.pdo_sqlite", "php82Extensions.zip", "nodejs_18", "npm"]

[phases.install]
cmds = [
    "mkdir -p database",
    "touch database/database.sqlite",
    "composer install --no-dev --optimize-autoloader",
    "npm ci"
]

[phases.build]
cmds = [
    "php artisan key:generate --force",
    "npm run build",
    "php artisan migrate --force",
    "php artisan db:seed --force",
    "php artisan config:cache",
    "php artisan route:cache"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
